import "./globals.css";
import { Tajawal, Orbitron } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

const tajawal = Tajawal({
  weight: "400",
  subsets: ["arabic", "latin"],
  variable: "--font-tajawal",
});
const orbitron = Orbitron({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-orbitron",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tajawal.variable} ${orbitron.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
