import Footer from "../components/footer/Footer";
import Navbar from "../components/header/Navbar";
import "./globals.css";
import { Tajawal } from "next/font/google";

 
const tajawal = Tajawal({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
} ) {
  return (
    <html lang="en">
      <body className={tajawal.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
